version: "3"
services: 
  fptp: 
    build:
      context: .
      dockerfile: Dockerfile
    tty: true 
    ports:
      - 8481:8481
    networks:
      - makuhari_city
networks:
  makuhari_city:
    external: true
